name       : quilt
version    : '0.65'
release    : 5
source     :
    - http://download.savannah.gnu.org/releases/quilt/quilt-0.65.tar.gz : f6cbc788e5cbbb381a3c6eab5b9efce67c776a8662a7795c7432fd27aa096819
license    :
    - GPL-2.0
summary    : Scripts for working with series of patches
builddeps  :
    - diffstat
component  : system.devel
description: |
    Quilt allows you to easily manage large numbers of patches by keeping
    track of the changes each patch makes. Patches can be applied,
    un-applied, refreshed, and more.
setup      : |
    %patch -p1 < $pkgfiles/0001-Support-a-stateless-configuration.patch
    %configure --without-rpmbuild \
               --without-sendmail
build      : |
    %make
install    : |
    %make_install BUILD_ROOT=$installdir
